name: Deploy Yew App
run-name: Deploying Yew App
on: [push]
jobs:
  build_and_deploy:
    environment: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Install rustup toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
            toolchain: stable
      - run: rustup target add wasm32-unknown-unknown
      - name: trunk-action
        uses: jetli/trunk-action@v0.4.0
      - run: sudo apt install nodejs npm
      - run: npm install -D tailwindcss postcss autoprefixer
      - name: Checkout repo
        uses: actions/checkout@v3
      - run: cd ${{ github.workspace }}
      - run: trunk build
      - uses: actions/upload-pages-artifact@v1.0.7
        with:
            path: "dist/"

      
