name: Deploy Yew App
run-name: Deploying Yew App
on:
  push:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install rustup toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
            toolchain: stable
      - run: rustup target add wasm32-unknown-unknown
      - name: trunk-action
        uses: jetli/trunk-action@v0.4.0
      - run: sudo apt install nodejs npm
      - run: npm install -D tailwindcss postcss autoprefixer
      - name: Checkout repo
        uses: actions/checkout@v3
      - run: cd ${{ github.workspace }}
      - run: trunk build
      - uses: actions/upload-pages-artifact@v1.0.7
        with:
            path: "dist/"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
